In [9]:
# Example notebook structure
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, confusion_matrix, accuracy_score, log_loss
import time


# Load data



In [10]:
X = np.load('cifar10_features.npy')
y = np.load('cifar10_labels.npy')



# Split data




In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Softmax Logistic Regression


In [12]:
beginning_time = time.time()
softmax = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=5000)
softmax.fit(X_train, y_train)
softmax_time = time.time() - beginning_time

softmax_predictions = softmax.predict(X_test)
softmax_accuracy = accuracy_score(y_test, softmax_predictions)
softmax_f1 = f1_score(y_test, softmax_predictions, average='weighted')
softmax_log_loss = log_loss(y_test, softmax.predict_proba(X_test))




# One-vs-all Logistic Regression



In [13]:
beginning_time = time.time()
oneVsAll = LogisticRegression(multi_class='ovr', solver='lbfgs', max_iter=5000)
oneVsAll.fit(X_train, y_train)
oneVsAll_time = time.time() - beginning_time

oneVsAll_predictions = oneVsAll.predict(X_test)
oneVsAll_accuracy = accuracy_score(y_test, oneVsAll_predictions)
oneVsAll_f1 = f1_score(y_test, oneVsAll_predictions, average='weighted')
oneVsAll_log_loss = log_loss(y_test, oneVsAll.predict_proba(X_test))


# Print results


In [14]:
print(f"Softmax Accuracy: {softmax_accuracy}, Time: {softmax_time} seconds, Log Loss: {softmax_log_loss}, F1 Score: {softmax_f1}")
print(f"One-vs-All Accuracy: {oneVsAll_accuracy}, Time: {oneVsAll_time} seconds, Log Loss: {oneVsAll_log_loss}, F1 Score: {oneVsAll_f1}")


Softmax Accuracy: 0.9629333333333333, Time: 4.4742701053619385 seconds, Log Loss: 0.10768597462451053, F1 Score: 0.9629646467647454
One-vs-All Accuracy: 0.961, Time: 2.1810848712921143 seconds, Log Loss: 0.13459723836922313, F1 Score: 0.9610172357351848



# Confusion Matrix for one vs all



In [15]:
oneVsAllMatrix = confusion_matrix(y_test, oneVsAll_predictions)
print(oneVsAllMatrix)

[[1402    2   13    5    5    3    2   10   17    5]
 [   2 1464    4    1    0    1    0    1    5    7]
 [  11    1 1370   15   16   15    5    3    1    3]
 [  14    5   15 1450   12   51    5   10    3    4]
 [   6    0   13   15 1466    5    4    9    0    1]
 [   2    3   13   45   12 1437    8   11    2    1]
 [   5    5    9   17    4    6 1415    0    1    1]
 [   3    0    4   17    9    7    0 1456    0    1]
 [  13    2    1    5    1    0    2    0 1480    6]
 [  12    7    5    6    0    4    2    3    5 1475]]



# Train a specialized model for the hardest-to-distinguish class pair


In [16]:
class_pair = (8, 9)
class_pair_indices = np.where((y_train == class_pair[0]) | (y_train == class_pair[1]))

X_train_pair = X_train[class_pair_indices]
y_train_pair = y_train[class_pair_indices]

X_test_pair = X_test[np.where((y_test == class_pair[0]) | (y_test == class_pair[1]))]
y_test_pair = y_test[np.where((y_test == class_pair[0]) | (y_test == class_pair[1]))]

specialized_model = LogisticRegression(solver='lbfgs', max_iter=5000)
specialized_model.fit(X_train_pair, y_train_pair)

pair_predictions = specialized_model.predict(X_test_pair)
pair_accuracy = accuracy_score(y_test_pair, pair_predictions)
pair_f1 = f1_score(y_test_pair, pair_predictions, average='weighted')

print(f"Specialized Model Accuracy: {pair_accuracy}")
print(f"Specialized Model F1 Score: {pair_f1}")

Specialized Model Accuracy: 0.996038296467481
Specialized Model F1 Score: 0.996038296467481
